### ISSUE TITLE
Move BOTS file to /usr/share/package in debian package

### ISSUE THREAD

**Issue by rrenkert** [Intevation/intelmq-certbund-contact#16]
Following the [debian package policy](https://www.debian.org/doc/debian-policy/ch-docs.html) the BOTS file should not be placed under ```/usr/share/doc``` since it is used for post processing.
As the policy states the file should be installed e.g. under ```/usr/share/packages``` and then symlinked.

**Comment by wagner-certat** [comment]
BOTS disappeares in IntelMQ 3.0, so I doubt that this change now is worth the effort.

**Comment by wagner-intevation** [comment]
This issue is obsolete with the upgrade to 3.0.0
